# Generated by Django 5.2 on 2025-08-22 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('address', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_of_study', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=10)),
                ('grade_12_certificate', models.FileField(upload_to='documents/certificates/')),
                ('transcript', models.FileField(upload_to='documents/transcripts/')),
                ('acceptance_letter', models.FileField(upload_to='documents/acceptance_letters/')),
                ('school_fee_structure', models.FileField(upload_to='documents/fee_structures/')),
                ('id_card', models.FileField(upload_to='documents/ids/')),
                ('character_reference_1', models.FileField(upload_to='documents/references/')),
                ('character_reference_2', models.FileField(upload_to='documents/references/')),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='applications.applicantprofile')),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.course')),
                ('institution', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institutions.institution')),
            ],
        ),
    ]
