# Generated by Django 5.2 on 2025-09-07 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_alter_application_options_alter_application_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
        migrations.AddField(
            model_name='application',
            name='reviewer_note',
            field=models.TextField(blank=True),
        ),
    ]
