# Generated by Django 5.2 on 2025-09-07 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_applicantprofile_photo_application_reviewer_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
