# Generated by Django 5.2 on 2025-09-14 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_application_ai_summary'),
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='institution',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='institutions.institution'),
        ),
    ]
