# Generated by Django 5.2 on 2025-09-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_alter_application_institution'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='expression_of_interest',
            field=models.FileField(blank=True, null=True, upload_to='documents/expression_letters/'),
        ),
        migrations.AddField(
            model_name='application',
            name='origin_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='origin_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='origin_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_annual_income',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_income_source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='parent_salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='residency_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='residency_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='residency_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='application',
            name='residency_years',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='application',
            name='student_company',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='student_employed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='application',
            name='student_job_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='application',
            name='student_salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
