# Generated by Django 5.2 on 2025-12-11 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_faq_policypage'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='active_student_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_llg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='current_residential_area',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='duration_living_in',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='elementary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_elementary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_highschool_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_llg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_primary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='father_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='grade12_certificate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_elementary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_elementary_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_highschool_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_highschool_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_llg',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_nationality',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_primary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_primary_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='mother_village',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='nid_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='primary_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='secondary_school_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='sim_card_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='tesas_category',
            field=models.CharField(blank=True, choices=[('HECAS', 'HECAS'), ('AES', 'AES'), ('SS', 'SS')], max_length=10),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='year_completed_grade12',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
