# Generated by Django 5.2 on 2025-12-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_applicantprofile_active_student_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='expression_of_interest',
        ),
        migrations.AddField(
            model_name='application',
            name='statedec',
            field=models.FileField(blank=True, null=True, upload_to='documents/statedec/'),
        ),
    ]
