# Generated by Django 5.2 on 2025-12-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_remove_application_expression_of_interest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='is_continuing',
            field=models.BooleanField(default=False),
        ),
    ]
