# Generated by Django 5.2 on 2026-01-09 07:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='applicationreview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Application Review', 'verbose_name_plural': 'Application Reviews'},
        ),
        migrations.AddField(
            model_name='applicationreview',
            name='decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='applicationreview',
            unique_together={('application', 'reviewer')},
        ),
    ]
