# Generated by Django 5.2 on 2026-01-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0013_alter_applicationreview_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='acceptance_letter',
            field=models.FileField(blank=True, null=True, upload_to='documents/acceptance_letters/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='character_reference_1',
            field=models.FileField(blank=True, null=True, upload_to='documents/references/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='character_reference_2',
            field=models.FileField(blank=True, null=True, upload_to='documents/references/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='grade_12_certificate',
            field=models.FileField(blank=True, null=True, upload_to='documents/certificates/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='id_card',
            field=models.FileField(blank=True, null=True, upload_to='documents/ids/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='school_fee_structure',
            field=models.FileField(blank=True, null=True, upload_to='documents/fee_structures/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='transcript',
            field=models.FileField(blank=True, null=True, upload_to='documents/transcripts/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='year_of_study',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applicationreview',
            name='note',
            field=models.TextField(blank=True),
        ),
    ]
