# Generated by Django 5.2 on 2026-01-11 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_acceptance_letter_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='sim_card_number',
        ),
    ]
