# Generated by Django 5.2 on 2026-01-11 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_remove_applicantprofile_sim_card_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicantprofile',
            old_name='address',
            new_name='postal_address',
        ),
        migrations.RemoveField(
            model_name='applicantprofile',
            name='current_address',
        ),
    ]
