# Generated by Django 5.2 on 2026-01-11 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_rename_address_applicantprofile_postal_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='origin_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='origin_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='origin_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='residency_district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='residency_province',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='residency_ward',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantprofile',
            name='residency_years',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
