# Generated by Django 5.2 on 2026-01-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0017_applicantprofile_origin_district_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='residency_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
