# Generated by Django 5.2 on 2026-01-11 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0018_alter_applicantprofile_residency_years'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='residency_years',
        ),
    ]
