# Generated by Django 5.2 on 2026-01-11 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0019_remove_application_residency_years'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'permissions': [('view_financials', 'Can view financial details for applications')]},
        ),
    ]
