# Generated by Django 5.2 on 2026-01-13 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_application_options_and_more'),
        ('institutions', '0012_institution_account_type_institution_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='applicationreview',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='application',
            name='statedec',
        ),
        migrations.AddField(
            model_name='application',
            name='statdec',
            field=models.FileField(blank=True, null=True, upload_to='documents/statdec/'),
        ),
        migrations.AlterField(
            model_name='application',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='institutions.institution'),
        ),
    ]
