# Generated by Django 5.2 on 2026-01-13 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0022_alter_applicationreview_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='residency_years',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
