# Generated by Django 5.2 on 2026-01-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0023_application_residency_years'),
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('institution', models.CharField(blank=True, max_length=200)),
                ('course', models.CharField(blank=True, max_length=200)),
                ('year_of_study', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
