# Generated by Django 5.2 on 2026-01-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0024_legacystudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='legacystudent',
            name='tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
