# Generated by Django 5.2 on 2026-01-14 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0025_legacystudent_tuition_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='active_student_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='current_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='documents/photos/'),
        ),
    ]
