# Generated by Django 5.2 on 2026-01-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0026_application_active_student_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='has_edited',
            field=models.BooleanField(default=False),
        ),
    ]
