# Generated by Django 5.2 on 2026-01-15 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0027_application_has_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_photos/'),
        ),
    ]
