# Generated by Django 5.2 on 2026-01-15 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0028_applicantprofile_face_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprofile',
            name='face_photo',
        ),
        migrations.AlterField(
            model_name='application',
            name='face_photo',
            field=models.ImageField(blank=True, null=True, upload_to='face_photos/'),
        ),
    ]
