# Generated by Django 5.2 on 2026-01-16 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0029_remove_applicantprofile_face_photo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='face_photo',
        ),
    ]
