# Generated by Django 5.2 on 2026-01-16 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0030_remove_application_face_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applications_open', models.BooleanField(default=True)),
                ('close_at', models.DateTimeField(blank=True, null=True)),
                ('rollover_at', models.DateTimeField(blank=True, null=True)),
                ('legacy_lookup_enabled', models.BooleanField(default=True)),
            ],
        ),
    ]
