# Generated by Django 5.2 on 2026-01-16 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0031_applicationconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], null=True),
        ),
        migrations.AlterField(
            model_name='legacystudent',
            name='year_of_study',
            field=models.IntegerField(blank=True, choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3'), (4, 'Year 4'), (5, 'Year 5')], null=True),
        ),
    ]
