# Generated by Django 5.2 on 2025-12-20 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_code', models.CharField(help_text='e.g., 272-4401-1-101', max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('allocation_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fiscal_year', models.IntegerField(default=2025)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='payment',
            name='batch_number',
            field=models.CharField(blank=True, help_text='IFMS Batch ID', max_length=50),
        ),
        migrations.AddField(
            model_name='payment',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vendor_code',
            field=models.CharField(blank=True, help_text="The Institution's ID in IFMS", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMMITTED', 'Committed (FF3)'), ('PAID', 'Paid/Processed (FF4)'), ('CANCELLED', 'Cancelled')], default='COMMITTED', max_length=15),
        ),
        migrations.AddField(
            model_name='payment',
            name='budget_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.budgetvote'),
        ),
    ]
