# Generated by Django 5.2 on 2026-01-03 12:20

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0012_application_created_at_and_more'),
        ('finance', '0002_budgetvote_remove_payment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScholarshipOfficerView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(max_length=15)),
                ('budget_vote_code', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Scholarship Officer View',
                'verbose_name_plural': 'Scholarship Officer Views',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=150)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='FillablePDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('template_type', models.CharField(choices=[('FF3', 'FF3 - Commitment'), ('FF4', 'FF4 - Expenditure')], max_length=4)),
                ('template_id', models.CharField(help_text='External service template id (2pdf) or local identifier', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Fillable PDF Template',
                'verbose_name_plural': 'Fillable PDF Templates',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('FF3', 'Commitment Report'), ('FF4', 'Expenditure Report')], max_length=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file_path', models.CharField(help_text='Path to CSV/Excel export', max_length=255)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='GeneratedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated_pdfs/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('external_id', models.CharField(blank=True, help_text='ID returned by 2pdf (if any)', max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Generated PDF',
                'verbose_name_plural': 'Generated PDFs',
                'ordering': ('-generated_at',),
            },
        ),
        migrations.CreateModel(
            name='PDFAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GENERATED', 'Generated'), ('VIEWED', 'Viewed'), ('DOWNLOADED', 'Downloaded'), ('SIGNED_UPLOADED', 'Signed Uploaded'), ('SAVED_EDIT', 'Saved Edited')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'PDF Audit',
                'verbose_name_plural': 'PDF Audits',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='SignedPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(upload_to='signed_pdfs/%Y/%m/%d/')),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Signed PDF',
                'verbose_name_plural': 'Signed PDFs',
                'ordering': ('-uploaded_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='budgetvote',
            options={'ordering': ('-fiscal_year', 'vote_code'), 'verbose_name': 'Budget Vote', 'verbose_name_plural': 'Budget Votes'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Payment', 'verbose_name_plural': 'Payments'},
        ),
        migrations.AddField(
            model_name='payment',
            name='form11_identifier',
            field=models.CharField(blank=True, help_text='Form 11 identifier (Governor sign-off)', max_length=128),
        ),
        migrations.AddField(
            model_name='payment',
            name='section_32_officer',
            field=models.CharField(blank=True, help_text='Officer certifying availability of funds', max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='treasury_release_date',
            field=models.DateField(blank=True, help_text='Date Treasury confirms payment processed', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='vote_item_code',
            field=models.CharField(blank=True, help_text='Vote/Item code used in IFMS', max_length=64),
        ),
        migrations.AlterField(
            model_name='budgetvote',
            name='allocation_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetvote',
            name='vote_code',
            field=models.CharField(db_index=True, help_text='e.g., 272-4401-1-101', max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='budget_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='finance.budgetvote'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, help_text='Date of payment or commitment (FF3/FF4)', null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('COMMITTED', 'Committed (FF3)'), ('PAID', 'Paid/Processed (FF4)'), ('CANCELLED', 'Cancelled')], db_index=True, default='COMMITTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='budgetvote',
            unique_together={('vote_code', 'fiscal_year')},
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='finance_pay_status_cb601d_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['batch_number'], name='finance_pay_batch_n_503131_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['vendor_code'], name='finance_pay_vendor__40cf07_idx'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='budget_vote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.budgetvote'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fillablepdftemplate',
            unique_together={('template_type', 'template_id')},
        ),
        migrations.AddField(
            model_name='financialreport',
            name='generated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedpdf',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generatedpdf',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_pdfs', to='finance.payment'),
        ),
        migrations.AddField(
            model_name='generatedpdf',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fillablepdftemplate'),
        ),
        migrations.AddField(
            model_name='pdfaudit',
            name='generated_pdf',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finance.generatedpdf'),
        ),
        migrations.AddField(
            model_name='pdfaudit',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='signedpdf',
            name='generated_pdf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signed_versions', to='finance.generatedpdf'),
        ),
        migrations.AddField(
            model_name='signedpdf',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
