# Generated by Django 5.2 on 2026-01-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_alter_application_acceptance_letter_and_more'),
        ('finance', '0003_scholarshipofficerview_auditlog_fillablepdftemplate_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['application'], name='finance_pay_applica_160507_idx'),
        ),
    ]
