# Generated by Django 5.2 on 2026-01-13 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0021_alter_application_options_and_more'),
        ('finance', '0004_payment_finance_pay_applica_160507_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='financialreport',
            name='generated_by',
        ),
        migrations.DeleteModel(
            name='ScholarshipOfficerView',
        ),
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='budgetvote',
            options={'ordering': ('-fiscal_year', 'vote_code')},
        ),
        migrations.AlterModelOptions(
            name='fillablepdftemplate',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='generatedpdf',
            options={'ordering': ('-generated_at',)},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ('-created_at',)},
        ),
        migrations.AlterModelOptions(
            name='pdfaudit',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AlterModelOptions(
            name='signedpdf',
            options={'ordering': ('-uploaded_at',)},
        ),
        migrations.RemoveIndex(
            model_name='payment',
            name='finance_pay_applica_160507_idx',
        ),
        migrations.AddField(
            model_name='generatedpdf',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.payment'),
        ),
        migrations.AlterField(
            model_name='budgetvote',
            name='vote_code',
            field=models.CharField(db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='fillablepdftemplate',
            name='template_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='external_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='generatedpdf',
            name='status',
            field=models.CharField(choices=[('READY', 'Ready'), ('FAILED', 'Failed'), ('PENDING', 'Pending'), ('PROCESSING', 'Processing')], default='PENDING', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='payment',
            name='batch_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='payment',
            name='form11_identifier',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='section_32_officer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='treasury_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vendor_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='vote_item_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddConstraint(
            model_name='payment',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_0'),
        ),
        migrations.DeleteModel(
            name='FinancialReport',
        ),
    ]
