# Generated by Django 5.2 on 2026-01-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0003_course_code_institution_account_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('institution', 'code')},
        ),
    ]
