# Generated by Django 5.2 on 2026-01-04 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0005_alter_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
