# Generated by Django 5.2 on 2026-01-09 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0009_alter_institution_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(default=411, max_length=10, unique=True),
        ),
    ]
