# Generated by Django 5.2 on 2026-01-11 02:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0010_alter_institution_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='institution',
            name='code',
            field=models.CharField(default='411-00', max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[A-Z0-9\\-]+$', 'Only letters, numbers and hyphens allowed')]),
        ),
    ]
