# Generated by Django 5.2 on 2026-01-13 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0011_alter_institution_options_alter_institution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='institution',
            name='account_type',
            field=models.CharField(blank=True, choices=[('CHEQ', 'Cheque'), ('SAV', 'Savings')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=12),
        ),
        migrations.AddField(
            model_name='institution',
            name='tin',
            field=models.CharField(blank=True, help_text='Taxpayer Identification Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='institution',
            name='vendor_code',
            field=models.CharField(blank=True, help_text='IFMS Vendor Code', max_length=50, null=True),
        ),
    ]
