# Generated by Django 5.2 on 2026-01-16 11:10

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('institutions', '0012_institution_account_type_institution_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='total_tuition_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
